name: release-workflow.yaml

on:
  push:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  build-and-sync:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Install buf
        uses: bufbuild/buf-setup-action@v1.50.0

      - name: Calculate New Version
        id: calculate-version
        uses: ietf-tools/semver-action@v1
        with:
          token: ${{ github.token }}
          branch: main

      - name: Buf Generate
        run: |
          buf generate

      - name: Create Release Branch, Commit, Tag, and Push
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Create a new branch for the release, commit the generated client libraries, tag the release, and push to origin
          CURRENT_BRANCH=$(git branch --show-current)
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git checkout -b "release/${{ steps.calculate-version.outputs.next }}"
          git add gen/
          git commit -m "Release ${{ steps.calculate-version.outputs.next }}: Include generated client libraries"
          git tag -a ${{ steps.calculate-version.outputs.next }} -m "Release ${{ steps.calculate-version.outputs.next }}"
          git checkout "$CURRENT_BRANCH"
          git branch -D "release/${{ steps.calculate-version.outputs.next }}"
          git push origin ${{ steps.calculate-version.outputs.next }}
          gh release create ${{ steps.calculate-version.outputs.next }} \
              --repo ${{github.repository}} \
              --title "${{ steps.calculate-version.outputs.next }}" \
              --generate-notes